keywords:
  - ICJ
  - ICC Prosecutor
  - UNCLOS
  - Israel settlements
  - investment arbitration
  - EEZ
  - innocent passage
  - genocide convention
  - AI international law

blogs:
  - https://opiniojuris.org/feed/
  - https://www.ejiltalk.org/feed/
  - https://lieber.westpoint.edu/feed/
  - https://www.asymmetrichaicut.com/feed/
  - https://armedgroups.org/feed/
  - https://www.articlesofwar.org/feed/

names:
  - Aeyal Gross
  - Yuval Shany
  - Eyal Benvenisti
  - Michael Sfard
  - Malcolm Shaw
  - Philippe Sands
  - Omri Rachum-Twaig
